# Generated by Django 5.1.4 on 2025-01-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_options_alter_discount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="activate_date",
            field=models.DateTimeField(
                blank=True,
                help_text="keep empty for an immediate activation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="deactivate_date",
            field=models.DateTimeField(
                blank=True, help_text="keep empty for indefinite activation", null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Inactive"), (1, "Active")],
                default=1,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="activate_date",
            field=models.DateTimeField(
                blank=True,
                help_text="keep empty for an immediate activation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="deactivate_date",
            field=models.DateTimeField(
                blank=True, help_text="keep empty for indefinite activation", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Inactive"), (1, "Active")],
                default=1,
                verbose_name="status",
            ),
        ),
    ]
